// components/ui/CharReveal.tsx
type CharRevealProps = {
  text: string;
  baseDelay?: number;
  stagger?: number;
  className?: string;
};

export function CharReveal({ text, baseDelay = 0.8, stagger = 0.05, className }: CharRevealProps) {
  const words = text.split(" ");
  return (
    <span aria-label={text} className={className}>
      <span aria-hidden>
        {words.map((word, wi) => {
          const wordOffset = words.slice(0, wi).reduce((acc, w) => acc + w.length + 1, 0);
          return (
            <span key={wi}>
              {wi > 0 ? " " : null}
              <span className="inline-block whitespace-nowrap">
                {word.split("").map((ch, i) => (
                  <span
                    key={i}
                    className="inline-block overflow-hidden align-bottom pt-[0.05em] pb-[0.2em] -my-[0.2em]"
                  >
                    <span
                      className="block animate-char-reveal"
                      style={{
                        animationDelay: `${(baseDelay + (wordOffset + i) * (stagger ?? 0.05)).toFixed(2)}s`,
                      }}
                    >
                      {ch}
                    </span>
                  </span>
                ))}
              </span>
            </span>
          );
        })}
      </span>
    </span>
  );
}

// src/lib/components/ui/CharReveal.svelte
<script lang="ts">
	interface Props {
		text: string;
		baseDelay?: number;
		stagger?: number;
		className?: string;
	}

	let { text, baseDelay = 0.8, stagger = 0.05, className }: Props = $props();

	const words = $derived(text.split(' '));
	// Offsets precomputados en $derived: evita O(n²) slice/reduce en el template.
	const wordOffsets = $derived.by(() => {
		const offsets: number[] = [];
		let acc = 0;
		for (const w of words) {
			offsets.push(acc);
			acc += w.length + 1;
		}
		return offsets;
	});
</script>

<span aria-label={text} class={className}>
	<span aria-hidden="true">
		{#each words as word, wi (wi)}
			<span>
				{#if wi > 0}<span>{' '}</span>{/if}
				<span class="inline-block whitespace-nowrap">
					{#each word.split('') as ch, i (`${wi}-${i}`)}
						<span class="inline-block overflow-hidden align-bottom -my-[0.2em] pt-[0.05em] pb-[0.2em]">
							<span
								class="block animate-char-reveal"
								style="animation-delay: {(baseDelay + (wordOffsets[wi] + i) * stagger).toFixed(2)}s"
							>
								{ch}
							</span>
						</span>
					{/each}
				</span>
			</span>
		{/each}
	</span>
</span>
