// src/lib/components/CustomCursor.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let enabled = $state(false);
	let hovering = $state(false);
	let pressed = $state(false);

	// Posición en variables planas (no $state): el loop rAF muta el DOM
	// directamente y evita re-renders de Svelte a 60fps (over-reactivity).
	let x = -200;
	let y = -200;
	let dotX = -200;
	let dotY = -200;
	let ringX = -200;
	let ringY = -200;
	let raf = 0;
	let dotEl: HTMLDivElement | null = $state(null);
	let ringEl: HTMLDivElement | null = $state(null);

	function tick() {
		dotX += (x - dotX) * 0.5;
		dotY += (y - dotY) * 0.5;
		ringX += (x - ringX) * 0.25;
		ringY += (y - ringY) * 0.25;
		dotEl?.style.setProperty('transform', `translate(${dotX}px, ${dotY}px) translate(-50%, -50%)`);
		ringEl?.style.setProperty(
			'transform',
			`translate(${ringX}px, ${ringY}px) translate(-50%, -50%) scale(${pressed ? 0.6 : hovering ? 1.9 : 1})`
		);
		raf = requestAnimationFrame(tick);
	}

	onMount(() => {
		if (!window.matchMedia('(pointer: fine)').matches) return;
		enabled = true;
		document.body.classList.add('cursor-live');

		const onMove = (e: PointerEvent) => {
			x = e.clientX;
			y = e.clientY;
		};
		const onOver = (e: PointerEvent) => {
			const target = e.target as HTMLElement | null;
			hovering = Boolean(target?.closest("[data-cursor='hover']"));
		};
		const onDown = () => (pressed = true);
		const onUp = () => (pressed = false);

		window.addEventListener('pointermove', onMove, { passive: true });
		window.addEventListener('pointerover', onOver, { passive: true });
		window.addEventListener('pointerdown', onDown);
		window.addEventListener('pointerup', onUp);
		raf = requestAnimationFrame(tick);

		return () => {
			window.removeEventListener('pointermove', onMove);
			window.removeEventListener('pointerover', onOver);
			window.removeEventListener('pointerdown', onDown);
			window.removeEventListener('pointerup', onUp);
			cancelAnimationFrame(raf);
			document.body.classList.remove('cursor-live');
		};
	});
</script>

{#if enabled}
	<div class="pointer-events-none fixed inset-0 z-[200]" aria-hidden="true">
		<div
			bind:this={dotEl}
			class="absolute h-1.5 w-1.5 rounded-full bg-accent"
			style="transform: translate(-200px, -200px) translate(-50%, -50%)"
		></div>
		<div
			bind:this={ringEl}
			class="absolute h-9 w-9 rounded-full border border-accent/70"
			style="transform: translate(-200px, -200px) translate(-50%, -50%); background-color: {hovering
				? 'rgba(34,197,94,0.12)'
				: 'rgba(34,197,94,0)'}; transition: background-color 0.2s"
		></div>
	</div>
{/if}

// components/CustomCursor.tsx
"use client";

import { useEffect, useState } from "react";
import { motion, useMotionValue, useSpring } from "framer-motion";

export function CustomCursor() {
  const [enabled, setEnabled] = useState(false);
  const [hovering, setHovering] = useState(false);
  const [pressed, setPressed] = useState(false);

  const x = useMotionValue(-200);
  const y = useMotionValue(-200);
  const dotX = useSpring(x, { stiffness: 1400, damping: 75, mass: 0.3 });
  const dotY = useSpring(y, { stiffness: 1400, damping: 75, mass: 0.3 });
  const ringX = useSpring(x, { stiffness: 800, damping: 45, mass: 0.35 });
  const ringY = useSpring(y, { stiffness: 800, damping: 45, mass: 0.35 });

  useEffect(() => {
    if (!window.matchMedia("(pointer: fine)").matches) return;
    setEnabled(true);
    document.body.classList.add("cursor-live");

    const onMove = (e: PointerEvent) => {
      x.set(e.clientX);
      y.set(e.clientY);
    };
    const onOver = (e: PointerEvent) => {
      const target = e.target as HTMLElement | null;
      setHovering(Boolean(target?.closest("[data-cursor='hover']")));
    };
    const onDown = () => setPressed(true);
    const onUp = () => setPressed(false);

    window.addEventListener("pointermove", onMove, { passive: true });
    window.addEventListener("pointerover", onOver, { passive: true });
    window.addEventListener("pointerdown", onDown);
    window.addEventListener("pointerup", onUp);
    return () => {
      window.removeEventListener("pointermove", onMove);
      window.removeEventListener("pointerover", onOver);
      window.removeEventListener("pointerdown", onDown);
      window.removeEventListener("pointerup", onUp);
      document.body.classList.remove("cursor-live");
    };
  }, [x, y]);

  if (!enabled) return null;

  return (
    <div className="pointer-events-none fixed inset-0 z-[200]" aria-hidden>
      <motion.div
        className="absolute h-1.5 w-1.5 rounded-full bg-accent"
        style={{ x: dotX, y: dotY, translateX: "-50%", translateY: "-50%" }}
      />
      <motion.div
        className="absolute h-9 w-9 rounded-full border border-accent/70"
        style={{ x: ringX, y: ringY, translateX: "-50%", translateY: "-50%" }}
        animate={{
          scale: pressed ? 0.6 : hovering ? 1.9 : 1,
          backgroundColor: hovering ? "rgba(34,197,94,0.12)" : "rgba(34,197,94,0)",
        }}
        transition={{ type: "spring", stiffness: 320, damping: 22 }}
      />
    </div>
  );
}
